spring:
  application:
    name: ProductService

  datasource:
    url: jdbc:mysql://localhost:3306/product_db?allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9090
  management:
    tracing:
      sampling:
        probability: 1.0
zipkin:
  base-url: http://localhost:9411
  service:
    name: ProductService

server:
  port: 8080

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId},%X{spanId}]"
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8061/eureka}


